export const companies = 
[
'Infobip USA',
'Infobip China',
'Infobip Austria',
'Infobip Germany',
'Infobip UK',
'Infobip Macedonia',
'Infobip France',
'Infobip Portugal',
'Infobip Spain',
'Infobip Brasil',
'Infobip Sweden',
'Infobip Iceland',
'Infobip Canada',
'Infobip Mexico',
'Infobip Hungary',
'Infobip Russia',
'Infobip Norway',
'Infobip Hrvatska',
'Infobip Ukraine',
'Infobip Angola',
'Infobip Japan',
'Infobip Argentina',
'Infobip Saudi Arabia',
'Infobip Bosnia and Hercegovina',
'Infobip Czech republic',
'Infobip Slovakia',
'Infobip India',
'Infobip Serbia',
'Infobip Argentina',
'Infobip Australia',
'Infobip Cuba',
'Infobip Belgium',
'Infobip Netherlands',
'Infobip Denmark',
'Infobip Finland',
'Infobip Slovenia',
'Infobip Latvia',
'Infobip Italy',
'Infobip Turkey',
'Infobip Romania',
'Infobip Poland',
'Infobip Israel',
'Infobip Egypt',
'Infobip New Zeland',
'Infobip Estonia',
'Infobip Greece',
'Infobip Cyprus',
'Infobip Jamaica',
'Infobip Switzerland',
'Infobip Colombia',
'Infobip Chile',
'Infobip Chad',
'Infobip Bolivia',
'Infobip Belarus',
'Infobip Andorra',
'Infobip Greenland',
'Infobip Ireland',
'Infobip Korea',
'Infobip Monaco',
]